### ISSUE TITLE
Integration error: bring_shopping_list - Integration 'bring_shopping_list' not found.

### ISSUE THREAD

**Issue by MrThiemann** [dotKrad/hass_bring_shopping_list_component#7]
Hey,
when I try to install your integration I get this error message:
**Integration error: bring_shopping_list - Integration 'bring_shopping_list' not found.**

I put the following in my configuration.yaml:
```
bring_shopping_list:
  lists:
    - id: xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      name: Home
      locale: de-DE
```
